In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [54]:
unfil_data = pd.read_csv("csvs/Noisy_Student_Bag_Price_Prediction_Dataset.csv")

In [55]:
unfil_data

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,Jansport,Nylon,Small,2.0,No,Yes,Backpack,Green,13.340058,143.445135
1,Under Armour,Nylon,Large,4.0,Yes,Yes,Tote,Pink,5.918030,72.086319
2,Nike,Nylon,Large,NaN,No,Yes,Messenger,Red,24.088386,29.699631
3,Nike,Nylon,Small,1.0,Yes,No,Messenger,Pink,5.000000,27.181990
4,Under Armour,Leather,Small,8.0,Yes,No,NaN,Black,11.258172,71.953236
...,...,...,...,...,...,...,...,...,...,...
52495,Jansport,Nylon,Medium,3.0,No,Yes,Messenger,Gray,19.774853,61.140497
52496,Jansport,NaN,Small,8.0,No,Yes,Messenger,Red,29.822417,47.140186
52497,Jansport,Polyester,Large,10.0,No,Yes,Messenger,Red,13.269034,56.184138
52498,Adidas,Canvas,Large,5.0,No,No,Messenger,Green,28.132229,112.036966
52499,Nike,Canvas,Large,6.0,NaN,Yes,Tote,Black,28.414360,42.917005

In [56]:
for i in list(set(unfil_data["Size"])):
    print(f"{i} : \n{unfil_data[unfil_data["Size"]==i]["Price"].describe()}\n")

Medium :
count    15825.000000
mean        81.773964
std         39.121798
min         15.000000
25%         47.712028
50%         81.510554
75%        115.473006
max        150.000000
Name: Price, dtype: float64

Large :
count    15696.000000
mean        82.096981
std         39.252116
min         15.000000
25%         47.875040
50%         82.080143
75%        115.890710
max        150.000000
Name: Price, dtype: float64

Small :
count    15868.000000
mean        81.900187
std         39.182276
min         15.000000
25%         47.972321
50%         81.179448
75%        115.404022
max        150.000000
Name: Price, dtype: float64

nan :
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Price, dtype: float64

In [57]:
obj = [col for col in unfil_data.columns if unfil_data[col].dtype == "object"]
oe_data = unfil_data.copy()
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
oe_data[obj] = oe.fit_transform(unfil_data[obj])

In [ ]:
#from sklearn.impute import KNNImputer
#imputer = KNNImputer(n_neighbors=3)
#filled_data = imputer.fit_transform(oe_data)
filled_data = pd.read_csv("csvs/Noisy_Student_Bag_Price_Prediction_Dataset_filled.csv")

In [65]:
filled_data

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,1.0,2.000000,2.0,2.000000,0.000000,1.0,0.000000,3.0,13.340058,143.445135
1,4.0,2.000000,0.0,4.000000,1.000000,1.0,2.000000,4.0,5.918030,72.086319
2,2.0,2.000000,0.0,6.333333,0.000000,1.0,1.000000,5.0,24.088386,29.699631
3,2.0,2.000000,2.0,1.000000,1.000000,0.0,1.000000,4.0,5.000000,27.181990
4,4.0,1.000000,2.0,8.000000,1.000000,0.0,1.666667,0.0,11.258172,71.953236
...,...,...,...,...,...,...,...,...,...,...
52495,1.0,2.000000,1.0,3.000000,0.000000,1.0,1.000000,2.0,19.774853,61.140497
52496,1.0,2.333333,2.0,8.000000,0.000000,1.0,1.000000,5.0,29.822417,47.140186
52497,1.0,3.000000,0.0,10.000000,0.000000,1.0,1.000000,5.0,13.269034,56.184138
52498,0.0,0.000000,0.0,5.000000,0.000000,0.0,1.000000,3.0,28.132229,112.036966
52499,2.0,0.000000,0.0,6.000000,0.333333,1.0,2.000000,0.0,28.414360,42.917005

In [ ]:
for i in obj:
    filled_data[i] = filled_data[i].astype("int64")

In [68]:
filled_data

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price
0,1,2,2,2.000000,0,1,0,3,13.340058,143.445135
1,4,2,0,4.000000,1,1,2,4,5.918030,72.086319
2,2,2,0,6.333333,0,1,1,5,24.088386,29.699631
3,2,2,2,1.000000,1,0,1,4,5.000000,27.181990
4,4,1,2,8.000000,1,0,1,0,11.258172,71.953236
...,...,...,...,...,...,...,...,...,...,...
52495,1,2,1,3.000000,0,1,1,2,19.774853,61.140497
52496,1,2,2,8.000000,0,1,1,5,29.822417,47.140186
52497,1,3,0,10.000000,0,1,1,5,13.269034,56.184138
52498,0,0,0,5.000000,0,0,1,3,28.132229,112.036966
52499,2,0,0,6.000000,0,1,2,0,28.414360,42.917005

In [77]:
from sklearn.preprocessing import OneHotEncoder
ohe_data = filled_data.copy()
ohe = OneHotEncoder(sparse_output=False)
ohed = ohe.fit_transform(ohe_data[obj])
ohed = pd.DataFrame(ohed)
ohe_data = pd.concat([ohe_data, ohed], axis=1)

In [78]:
ohe_data.drop(obj, axis=1, inplace=True)

In [81]:
ohe_data.columns = ohe_data.columns.astype("str")

In [82]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = ohe_data.copy()
scaled_data = scaler.fit_transform(scaled_data)
scaled_data = pd.DataFrame(scaled_data, columns=ohe_data.columns)

In [83]:
scaled_data

,Compartments,Weight Capacity (kg),Price,0,1,2,3,4,5,6,...,15,16,17,18,19,20,21,22,23,24
0,-1.240984,-0.566077,1.598405,-0.485401,1.959149,-0.521228,-0.495055,-0.487706,-0.571661,-0.598442,...,1.046130,1.411974,-0.726503,-0.686775,-0.438321,-0.45315,-0.462616,2.182551,-0.436003,-0.434734
1,-0.532973,-1.568004,-0.254796,-0.485401,-0.510426,-0.521228,-0.495055,2.050415,-0.571661,-0.598442,...,1.046130,-0.708228,-0.726503,1.456081,-0.438321,-0.45315,-0.462616,-0.458179,2.293564,-0.434734
2,0.293040,0.884880,-1.355586,-0.485401,-0.510426,1.918545,-0.495055,-0.487706,-0.571661,-0.598442,...,1.046130,-0.708228,1.376458,-0.686775,-0.438321,-0.45315,-0.462616,-0.458179,-0.436003,2.300259
3,-1.594989,-1.691933,-1.420969,-0.485401,-0.510426,1.918545,-0.495055,-0.487706,-0.571661,-0.598442,...,-0.955905,-0.708228,1.376458,-0.686775,-0.438321,-0.45315,-0.462616,-0.458179,2.293564,-0.434734
4,0.883049,-0.847118,-0.258252,-0.485401,-0.510426,-0.521228,-0.495055,2.050415,-0.571661,1.671005,...,-0.955905,-0.708228,1.376458,-0.686775,2.281434,-0.45315,-0.462616,-0.458179,-0.436003,-0.434734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52495,-0.886978,0.302580,-0.539061,-0.485401,1.959149,-0.521228,-0.495055,-0.487706,-0.571661,-0.598442,...,1.046130,-0.708228,1.376458,-0.686775,-0.438321,-0.45315,2.161622,-0.458179,-0.436003,-0.434734
52496,0.883049,1.658938,-0.902651,-0.485401,1.959149,-0.521228,-0.495055,-0.487706,-0.571661,-0.598442,...,1.046130,-0.708228,1.376458,-0.686775,-0.438321,-0.45315,-0.462616,-0.458179,-0.436003,2.300259
52497,1.591060,-0.575665,-0.667778,-0.485401,1.959149,-0.521228,-0.495055,-0.487706,-0.571661,-0.598442,...,1.046130,-0.708228,1.376458,-0.686775,-0.438321,-0.45315,-0.462616,-0.458179,-0.436003,2.300259
52498,-0.178967,1.430774,0.782729,2.060153,-0.510426,-0.521228,-0.495055,-0.487706,1.749289,-0.598442,...,-0.955905,-0.708228,1.376458,-0.686775,-0.438321,-0.45315,-0.462616,2.182551,-0.436003,-0.434734
52499,0.175038,1.468860,-1.012328,-0.485401,-0.510426,1.918545,-0.495055,-0.487706,1.749289,-0.598442,...,1.046130,-0.708228,-0.726503,1.456081,2.281434,-0.45315,-0.462616,-0.458179,-0.436003,-0.434734

In [84]:
scaled_data["Price"]= ohe_data["Price"]

In [92]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
minmax_data = scaled_data.copy()
minmax_data = scaler.fit_transform(minmax_data)
minmax_data=pd.DataFrame(minmax_data)

In [93]:
minmax_data

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0.111111,0.333602,0.951445,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.333333,0.036721,0.422862,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.592593,0.763535,0.108886,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.000000,0.000000,0.090237,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.777778,0.250327,0.421876,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52495,0.222222,0.590994,0.341781,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
52496,0.777778,0.992897,0.238075,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
52497,1.000000,0.330761,0.305068,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
52498,0.444444,0.925289,0.718792,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
52499,0.555556,0.936574,0.206793,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0

In [94]:
x = minmax_data.drop("Price", axis=1)
y = minmax_data["Price"]

KeyError: "['Price'] not found in axis"

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.metrics import mean_squared_error
trainx,testx,trainy,testy = train_test_split(x,y,test_size=0.2,random_state=0)
model = DecisionTreeRegressor(random_state=42)
param_grid = {
    'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],  # Valid for regressors
    'splitter': ['best', 'random'],
    'max_depth': [None, 10, 20, 30, 50],
    'min_samples_split': [2, 5, 10, 15],
    'min_samples_leaf': [1, 2, 4, 6],
    'max_features': [None, 'sqrt', 'log2'],
    'ccp_alpha': [0.0, 0.01, 0.1, 0.2]
}
# Randomized Search
random_search = RandomizedSearchCV(estimator=model, param_distributions=param_grid, 
                                   n_iter=50, cv=5, n_jobs=-1, scoring='accuracy', verbose=2, random_state=42)
random_search.fit(trainx,trainy)

# Best Parameters
print("Best Hyperparameters (Randomized Search):", random_search.best_params_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits